imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    web_path: %kernel.root_dir%/../web
    rtg.twig_extension.class: RTG\AppBundle\Services\Extension\TwigExtension

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: v1.2.7
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'RTGAppBundle:Form:customFormTheme.html.twig'
    globals:
        fb_app_id: %facebook_app_id%
        web_path: %web_path%
        brand_name: %brand_name%
services:
    rtg.twig_extension:
        class: %rtg.twig_extension.class%
        tags:
            - { name: twig.extension }
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ RTGAppBundle, RTGBlogBundle ]
    filters:
        cssrewrite: ~
        lessphp:
            file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
            apply_to: "\.less$"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    port:      %mailer_port%
    password:  %mailer_password%
    encryption: ssl
    auth_mode:  login
    logging:  "%kernel.debug%"

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: RTG\UserBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        form:
            type: fos_user_registration
        confirmation:
            enabled: true
            from_email:
                address: %noreply_address%
                sender_name: Admin de restartthegame.com
            template: RTGUserBundle:User:registration.email.twig

avalanche_imagine:
    filters:
        article-tb:
            type:    thumbnail
            options: { size: [240, 90], mode: outbound, quality: 100, format: png }
        tb-128x128:
            type:    thumbnail
            options: { size: [128, 128], mode: inset, quality: 100, format: png }
        tb-48x48:
            type:    thumbnail
            options: { size: [48, 48], mode: inset, quality: 100, format: png }

gregwar_captcha: ~

ivory_ck_editor:
    plugins:
        dialog:
            path:     "/bundles/rtgapp/js/ckeditor/plugins/dialog/"
            filename: "plugin.js"
        lineutils:
            path:     "/bundles/rtgapp/js/ckeditor/plugins/lineutils/"
            filename: "plugin.js"
        widget:
            path:     "/bundles/rtgapp/js/ckeditor/plugins/widget/"
            filename: "plugin.js"
        oembed:
            path:     "/bundles/rtgapp/js/ckeditor/plugins/oembed/"
            filename: "plugin.js"
    default_config: config_1
    configs:
        config_1:
            toolbar: custom
    toolbars:
        configs:
            custom: 
                - ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']
                - [NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl']
                - ['Link', 'Unlink', 'Anchor']
                - ['FLash', 'Table', 'HorizontalRule', 'SpecialChar', 'Smiley']
                - '/'
                - ['Styles', 'Format', 'Font', 'FontSize', 'TextColor', 'BGColor']
                - ['Maximize', 'ShowBlocks']
                - '/'
                - ['Source', '-', 'NewPage', '-', 'Templates']
                - ['PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']
                - ['Find', 'Replace', '-', 'SelectAll', '-', 'Scayt']
                - '/'
                - ['oembed', 'Image']
            full: 
                - ['Source', '-', 'NewPage', 'Preview', 'Print', '-', 'Templates']
                - ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']
                - ['Find', 'Replace', '-', 'SelectAll', '-', 'Scayt']
                - ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'SelectField', 'Button', 'ImageButton', 'HiddenField']
                - '/'
                - ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']
                - [NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl']
                - ['Link', 'Unlink', 'Anchor']
                - ['Image', 'FLash', 'Table', 'HorizontalRule', 'SpecialChar', 'Smiley', 'PageBreak', 'Iframe']
                - '/'
                - ['Styles', 'Format', 'Font', 'FontSize', 'TextColor', 'BGColor']
                - ['Maximize', 'ShowBlocks']
                - ['About']
            standard:
                - ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']
                - ['Scayt']
                - ['Link', 'Unlink', 'Anchor']
                - ['Image', 'Table', 'HorizontalRule', 'SpecialChar']
                - ['Maximize']
                - ['Source']
                - '/'
                - ['Bold', 'Italic', 'Strike', '-', 'RemoveFormat']
                - ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote']
                - ['Styles', 'Format', 'About']
            basic:
                - ['Bold', 'Italic']
                - ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent']
                - ['Link', 'Unlink']
                - ['About']