imports:
    - { resource: config.yml }
    - { resource: "@RTGBlogBundle/Resources/config/config_dev.yml" }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    channels: ["ip_mails"]
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
            channels: ["!ip_mails"]
        ip_mails:
            type: stream
            path: "%kernel.logs_dir%/ip_mails.log"
            level: info
            channels: ["ip_mails"]
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

assetic:
    use_controller: true

swiftmailer:
    delivery_address: %dev_delivery_address%
    disable_delivery: true
    spool: { type: memory }
