imports:
    - { resource: config.yml }
    - { resource: "@RTGBlogBundle/Resources/config/config_prod.yml" }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    channels: ["ip_mails"]
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
            channels: ["!ip_mails"]
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        ip_mails:
            type: stream
            path: "%kernel.logs_dir%/ip_mails.log"
            level: info
            channels: ["ip_mails"]