rtg_blog:
    resource: "@RTGBlogBundle/Controller/"
    type:     annotation
    prefix:   /

rtg_user:
    resource: "@RTGUserBundle/Controller/"
    type:     annotation
    prefix:   /

rtg_app:
    resource: "@RTGAppBundle/Controller/"
    type:     annotation
    prefix:   /

rtg_user:
    resource: "@RTGUserBundle/Resources/config/routing.yml"

_imagine:
    resource: .
    type:     imagine

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"