services:
    rtg_app.newsletter:
        class: RTG\AppBundle\Services\Newsletter
        arguments:
            em: @doctrine.orm.entity_manager
            mailer: @mailer
            templating: @templating
            newsletter_address: %newsletter_address%
            noreply_address: %noreply_address%
            brand_name: %brand_name%
    newsletter:
        alias: rtg_app.newsletter