parameters:
    rtg_site.newsletter.class: RTG\SiteBundle\Services\Newsletter
services:
    rtg_site.newsletter:
        class: %rtg_site.newsletter.class%
        arguments:
            em: '@doctrine.orm.entity_manager'
            mailer: '@mailer'
            newsletter_address: %newsletter_address%
            noreply_address: %noreply_address%
    newsletter:
        alias: rtg_site.newsletter